// Name : Muhammad Azmat
// Student ID : 23i-2651
// Assignment # 02

#include <iostream>
#include <string>
#include <cstdlib>
#include <ctime>

// Respected Sir, I have if else in this order
// if choice == 1
// if choice == 3
// if choice == 4
// if choice == 2
// This was just for my own convenience as I found the part(3) easier than the 2nd one.

using namespace std;

int choice;

int main()
{
    cout << " **** WELCOME TO GAME MENU **** " << endl;
    cout << " Please select the game you want to play " << endl;
    cout << " Press 1 for Higher or Lower " << endl;
    cout << " Press 2 for Rock-Paper-Scissors " << endl;
    cout << " Press 3 for Guess the numbers " << endl;
    cout << " Press 4 to Exit the Program " << endl;
    cin >> choice;

    if (choice != 1 && choice != 2 && choice != 3 && choice != 4) // input validation at menu.
        cout << " Please enter a valid number to continue further !! " << endl;
    else
    {
        if (choice == 1) // HIGHER OR LOWER
        {
            cout << " ** WELCOME TO THE THE GAME \"HIGHER OR LOWER\" ** " << endl;
            srand(time(0));
            int _1 = rand() % 20 + 1;
            int _2 = rand() % 20 + 1;
            cout << " Dear user, your two random numbers have been generated ! " << endl;
            cout << " The first random number generated is " << _1 << endl;
            cout << " *__* LETS SEE IF YOU WIN THE GAME OR NOT *__* " << endl;
            cout << " What do you think the next number will be ? " << endl;
            cout << " Enter 'H' if you think it is larger than Number 1 and press 'L' if it's small " << endl;
            char h_l;
            cin >> h_l;

            if (h_l != 'H' && h_l != 'h' && h_l != 'L' && h_l != 'l')
                cout << " ** INVALID ALPHABET. PLEASE TRY AGAIN ** " << endl;
            else
            {
                if (_1 < _2 && (h_l == 'H' || h_l == 'h'))
                    cout << " ** CONGRATULATIONS !! YOU HAVE MADE THE RIGHT GUESS ** " << endl;
                else
                {
                    if (_1 > _2 && (h_l == 'L' || h_l == 'l'))
                        cout << " ** CONGRATULATIONS !! YOU HAVE MADE THE RIGHT GUESS ** " << endl;
                    else
                    {
                        cout << " ****** WRONG GUESS. BETTER LUCK NEXT TIME ****** " << endl;
                        cout << " The second number generated was " << _2 << endl;
                    }
                }
            }
        }
        else
        {
            if (choice == 3) // RANDOM NUMBER GUESS GAME
            {
                cout << " **** WELCOME TO RANDOM NUMBERS GUESSING PROGRAM **** " << endl;
                cout << " IF YOU GUESS ALL THREE RIGHT, YOU ARE THE TRUE CHAMPION ** " << endl;

                srand(time(0));
                int random1 = rand() % 9 + 1;
                int random2 = rand() % 9 + 1;
                int random3 = rand() % 9 + 1;

                cout << " The random numbers have been generated by the computer ! " << endl;
                cout << " Lets start the game !! " << endl;
                /* cout << random1;  Just for test purposes, to see if the program is working flawlessly or not
                   cout << random2;
                   cout << random3; */

                int guess1, guess2, guess3;

                cout << " Please enter in your first guess " << endl;
                cin >> guess1;
                cout << " Please enter in your second guess " << endl;
                cin >> guess2;
                cout << " Please enter in your third guess " << endl;
                cin >> guess3;

                if ((guess1 > 0 && guess1 <= 9) && (guess2 > 0 && guess2 <= 9) && (guess3 > 0 && guess3 <= 9))
                {

                    if (guess1 == random1 && guess2 == random2 && guess3 == random3)
                        cout << " BRAVOO !! YOU GOT EACH GUESS RIGHT !!! " << endl;
                    else
                    {
                        if ((guess1 != random1 && guess1 != random2 && guess1 != random3) && (guess2 != random1 && guess2 != random2 && guess2 != random3) && (guess3 != random1 && guess3 && random2 && guess3 != random3))
                        {
                            cout << " SORRY !! you didn't even got a single right in any order. Better luck next time *** " << endl;
                            cout << " The correct numbers were: " << endl;
                            cout << random1 << " " << random2 << " " << random3 << endl;
                        }
                        else
                        {
                            if ((guess1 == random1 || guess1 == random2 || guess1 == random3) && (guess2 == random1 || guess2 == random2 || guess2 == random3) && (guess3 == random1 || guess3 == random2 || guess3 == random3))
                            {
                                cout << " NICE EFFORT !! YOU Got the guessing right but the order was not correct " << endl;
                                cout << " The correct order was : " << endl;
                                cout << random1 << endl;
                                cout << random2 << endl;
                                cout << random3 << endl;
                            }
                            else
                            {
                                if ((guess1 == random1 || guess1 == random2 || guess1 == random3) && (guess2 == random1 || guess2 == random2 || guess2 == random3) || (guess3 == random1 || guess3 == random2 || guess3 == random3) && (guess1 == random1 || guess1 == random2 || guess1 == random3) || (guess2 == random1 || guess2 == random2 || guess2 == random3) && (guess3 == random1 || guess3 == random2 || guess3 == random3))
                                    cout << " * You got only one right * " << endl;
                                else
                                {
                                    if ((guess1 == random1 || guess1 == random2 || guess1 == random3) || (guess2 == random1 || guess2 == random2 || guess2 == random3) || (guess3 == random1 || guess3 == random2 || guess3 == random3))
                                        cout << " ** You got only two right ** " << endl;
                                }
                            }
                        }
                    }
                }
                else
                {
                    cout << " ***** errror *****. You are not inputting numbers between 1 and 9 !! " << endl;
                }
            }
            else
            {
                if (choice == 4) // FINISH
                {
                    cout << " EXITING THE PROGRAM ********** " << endl;
                }
                else
                {
                    if (choice == 2) // ROCK PAPER SCISSORS.
                    {
                        srand(time(0));
                        int _1 = rand() % 3 + 1;
                        if (_1 == 1)
                            cout << " The random number generated : Paper " << endl;
                        else
                        {
                            if (_1 == 2)
                                cout << " The random number generated : Scissors " << endl;
                            else
                            {
                                if (_1 == 3)
                                    cout << " The random number generated : Rock " << endl;
                            }
                        }

                        cout << "  ***** WELCOME TO ROCK PAPER SCISSORS vs COMPUTER **** " << endl;
                        cout << " Are you ready to win ? " << endl;
                        char rps;
                        cout << " Enter P for paper, S for scissors, R for rock " << endl;
                        cin >> rps;
                        if (rps != 'P' && rps != 'p' && rps != 'S' && rps != 's' && rps != 'R' && rps != 'r')
                            cout << " Please enter a valid alphabet to continue !! " << endl;
                        else
                        {
                            if (_1 == 1 && (rps == 's' || rps == 'S'))
                                cout << " *** CONGRATULATIONS !! You have defeated computer in this game *** " << endl;
                            else
                            {
                                if (_1 == 2 && (rps == 'r' || rps == 'R'))
                                    cout << " *** CONGRATULATIONS !!1 You have defeated computer in this game *** " << endl;
                                else
                                {
                                    if (_1 == 3 && (rps == 'p' || rps == 'P'))
                                        cout << " *** CONGRATULATIONS !!1 You have defeated computer in this game *** " << endl;

                                    else
                                    {
                                        cout << " ***** THE MACHINE DEFEATED YOU IN A GAME OF ROCK PAPER SCISSORS ***** " << endl;
                                        cout << " Better Luck next time " << endl;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    return 0;
}
